blank_issues_enabled: false
contact_links:
  - name: Questions & Support
    url: https://github.com/abdu11aev-samandar/laravel-elevenlabs/discussions
    about: Savollar va umumiy muhokamalar uchun Discussions bo‘limidan foydalaning.
