blank_issues_enabled: false
contact_links:
  - name: Questions & Support
    url: https://github.com/your-org/laravel-elevenlabs-package/discussions
    about: Savollar va umumiy muhokamalar uchun Discussions bo‘limidan foydalaning.
